services:
  # Avalanche Remote Signer
  avax-remote-signer:
    image: avax-remote-signer:latest
    container_name: signer
    ports:
      - "9090:9090"  # gRPC port
    #  - "8080:8080"  # HTTP port
    volumes:
      - ./config-docker.yaml:/config/config.yaml:ro
      - ./keys:/keys:ro
    networks:
      - avalanche-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 60s
      timeout: 5s
      start_period: 5s
      retries: 3
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  # Avalanche Node
  avalanchego:
    image: avaplatform/avalanchego:latest
    platform: linux/amd64
    container_name: avago
    ports:
      - "9650:9650"  # HTTP API
      - "9651:9651"  # Staking port
    networks:
      - avalanche-network
    volumes:
      - ./avalanche-config:/root/.avalanchego/configs:ro
      - avalanche-data:/root/.avalanchego
    depends_on:
      avax-remote-signer:
        condition: service_healthy
    environment:
      - AVAGO_NETWORK_ID=fuji
    command:
      - sh
      - -c
      - |
        apt-get update &&
        apt-get install -y curl &&
        rm -f /root/.avalanchego/staking/signer.key &&
        /avalanchego/build/avalanchego --config-file=/root/.avalanchego/configs/node.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost:9650/ext/health"]
      interval: 60s
      timeout: 10s
      start_period: 120s
      retries: 3

networks:
  avalanche-network:
    driver: bridge

volumes:
  avalanche-data:
    driver: local
